package fr.archemod.blocks.baril;

public enum BarilType {

    HYDROMEL, BIERE_ROUSSE, RHUM, VIN_ROUGE, VIN_BLANC, BIERE_BRUNE, BIERRE_BLONDE, LAIT, EAU, LIQUIDE_JAUNE, LIQUIDE_ROUGE, LIQUIDE_VERT, LIQUIDE_ORANGE, LIQUIDE_BRUN, LIQUIDE_VIOLET, LIQUIDE_ROSE, LIQUIDE_INCOLORE, LIQUIDE_NOIR, VIDE;


}
